items:
- uid: system.fabric.exception
  id: exception
  children:
  - system.fabric.exception._com_exception
  - system.fabric.exception._duplicate_message_exception
  - system.fabric.exception._fabric_aggregate_exception
  - system.fabric.exception._fabric_backup_directory_not_empty_exception
  - system.fabric.exception._fabric_backup_in_progress_exception
  - system.fabric.exception._fabric_cannot_connect_exception
  - system.fabric.exception._fabric_connection_denied_exception
  - system.fabric.exception._fabric_delete_backup_file_failed_exception
  - system.fabric.exception._fabric_element_already_exists_exception
  - system.fabric.exception._fabric_element_not_found_exception
  - system.fabric.exception._fabric_endpoint_not_found_exception
  - system.fabric.exception._fabric_exception
  - system.fabric.exception._fabric_image_store_exception
  - system.fabric.exception._fabric_invalid_address_exception
  - system.fabric.exception._fabric_invalid_atomic_group_exception
  - system.fabric.exception._fabric_invalid_partition_key_exception
  - system.fabric.exception._fabric_key_not_found_exception
  - system.fabric.exception._fabric_message_too_large_exception
  - system.fabric.exception._fabric_missing_full_backup_exception
  - system.fabric.exception._fabric_node_primary_exception
  - system.fabric.exception._fabric_not_primary_exception
  - system.fabric.exception._fabric_not_readable_exception
  - system.fabric.exception._fabric_object_closed_exception
  - system.fabric.exception._fabric_replication_operation_too_large_exception
  - system.fabric.exception._fabric_server_authentication_failed_exception
  - system.fabric.exception._fabric_service_not_found_exception
  - system.fabric.exception._fabric_transient_exception
  - system.fabric.exception._invalid_reentrant_call_exception
  - system.fabric.exception._path_too_long_exception
  - system.fabric.exception._reentrant_actor_invalid_state_exception
  - system.fabric.exception._unauthorized_access_exception
  href: system.fabric.exception.yml
  langs:
  - java
  name: system.fabric.exception
  fullName: system.fabric.exception
  type: Namespace
  source:
    remote:
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/ComException.java
      branch: release_linux_5.3
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/ComException.java
  syntax:
    content: package system.fabric.exception
references:
- uid: system.fabric.exception._com_exception
  parent: system.fabric.exception
  href: system.fabric.exception._com_exception.yml
  name: ComException
  fullName: system.fabric.exception.ComException
  type: Class
  summary: <p>The exception that is thrown when an unrecognized HRESULT is returned from a COM method call. </p>
  syntax:
    content: public class ComException
- uid: system.fabric.exception._duplicate_message_exception
  parent: system.fabric.exception
  href: system.fabric.exception._duplicate_message_exception.yml
  name: DuplicateMessageException
  fullName: system.fabric.exception.DuplicateMessageException
  type: Class
  summary: <p>Exception indicates that Actor recieved Duplicate Message </p>
  syntax:
    content: public class DuplicateMessageException extends FabricException
- uid: system.fabric.exception._fabric_aggregate_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_aggregate_exception.yml
  name: FabricAggregateException
  fullName: system.fabric.exception.FabricAggregateException
  type: Class
  syntax:
    content: public class FabricAggregateException extends FabricException
- uid: system.fabric.exception._fabric_backup_directory_not_empty_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_backup_directory_not_empty_exception.yml
  name: FabricBackupDirectoryNotEmptyException
  fullName: system.fabric.exception.FabricBackupDirectoryNotEmptyException
  type: Class
  summary: <p>The exception that is thrown when the user provided backup directory is not empty. </p>
  syntax:
    content: public class FabricBackupDirectoryNotEmptyException extends FabricException
- uid: system.fabric.exception._fabric_backup_in_progress_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_backup_in_progress_exception.yml
  name: FabricBackupInProgressException
  fullName: system.fabric.exception.FabricBackupInProgressException
  type: Class
  summary: <p>The exception that is thrown when an attempt is made to create a backup when a previous backup is in progress. </p>
  syntax:
    content: public class FabricBackupInProgressException extends FabricException
- uid: system.fabric.exception._fabric_cannot_connect_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_cannot_connect_exception.yml
  name: FabricCannotConnectException
  fullName: system.fabric.exception.FabricCannotConnectException
  type: Class
  syntax:
    content: public class FabricCannotConnectException extends FabricException
- uid: system.fabric.exception._fabric_connection_denied_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_connection_denied_exception.yml
  name: FabricConnectionDeniedException
  fullName: system.fabric.exception.FabricConnectionDeniedException
  type: Class
  summary: <p>The exception that is thrown when connection is denied. </p>
  syntax:
    content: public class FabricConnectionDeniedException extends FabricException
- uid: system.fabric.exception._fabric_delete_backup_file_failed_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_delete_backup_file_failed_exception.yml
  name: FabricDeleteBackupFileFailedException
  fullName: system.fabric.exception.FabricDeleteBackupFileFailedException
  type: Class
  syntax:
    content: public class FabricDeleteBackupFileFailedException extends FabricException
- uid: system.fabric.exception._fabric_element_already_exists_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_element_already_exists_exception.yml
  name: FabricElementAlreadyExistsException
  fullName: system.fabric.exception.FabricElementAlreadyExistsException
  type: Class
  syntax:
    content: public class FabricElementAlreadyExistsException extends FabricException
- uid: system.fabric.exception._fabric_element_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_element_not_found_exception.yml
  name: FabricElementNotFoundException
  fullName: system.fabric.exception.FabricElementNotFoundException
  type: Class
  syntax:
    content: public class FabricElementNotFoundException extends FabricException
- uid: system.fabric.exception._fabric_endpoint_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_endpoint_not_found_exception.yml
  name: FabricEndpointNotFoundException
  fullName: system.fabric.exception.FabricEndpointNotFoundException
  type: Class
  summary: <p>Exception indicating that the specified endpoint was not found. </p>
  syntax:
    content: public class FabricEndpointNotFoundException extends FabricException
- uid: system.fabric.exception._fabric_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_exception.yml
  name: FabricException
  fullName: system.fabric.exception.FabricException
  type: Class
  syntax:
    content: public class FabricException
- uid: system.fabric.exception._fabric_image_store_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_image_store_exception.yml
  name: FabricImageStoreException
  fullName: system.fabric.exception.FabricImageStoreException
  type: Class
  syntax:
    content: public class FabricImageStoreException extends FabricException
- uid: system.fabric.exception._fabric_invalid_address_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_address_exception.yml
  name: FabricInvalidAddressException
  fullName: system.fabric.exception.FabricInvalidAddressException
  type: Class
  summary: <p>The exception that is thrown when an address is not recognized by Service fabric. </p>
  syntax:
    content: public class FabricInvalidAddressException extends FabricException
- uid: system.fabric.exception._fabric_invalid_atomic_group_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_atomic_group_exception.yml
  name: FabricInvalidAtomicGroupException
  fullName: system.fabric.exception.FabricInvalidAtomicGroupException
  type: Class
  syntax:
    content: public class FabricInvalidAtomicGroupException extends FabricException
- uid: system.fabric.exception._fabric_invalid_partition_key_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_partition_key_exception.yml
  name: FabricInvalidPartitionKeyException
  fullName: system.fabric.exception.FabricInvalidPartitionKeyException
  type: Class
  syntax:
    content: public class FabricInvalidPartitionKeyException extends FabricException
- uid: system.fabric.exception._fabric_key_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_key_not_found_exception.yml
  name: FabricKeyNotFoundException
  fullName: system.fabric.exception.FabricKeyNotFoundException
  type: Class
  syntax:
    content: public class FabricKeyNotFoundException extends FabricException
- uid: system.fabric.exception._fabric_message_too_large_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_message_too_large_exception.yml
  name: FabricMessageTooLargeException
  fullName: system.fabric.exception.FabricMessageTooLargeException
  type: Class
  syntax:
    content: public class FabricMessageTooLargeException extends FabricException
- uid: system.fabric.exception._fabric_missing_full_backup_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_missing_full_backup_exception.yml
  name: FabricMissingFullBackupException
  fullName: system.fabric.exception.FabricMissingFullBackupException
  type: Class
  summary: <p>The exception that is thrown when an attempt is made to create an incremental backup of the key-value store before an initial full backup is created. </p>
  syntax:
    content: public class FabricMissingFullBackupException extends FabricException
- uid: system.fabric.exception._fabric_node_primary_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_node_primary_exception.yml
  name: FabricNodePrimaryException
  fullName: system.fabric.exception.FabricNodePrimaryException
  type: Class
  syntax:
    content: public class FabricNodePrimaryException extends FabricException
- uid: system.fabric.exception._fabric_not_primary_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_not_primary_exception.yml
  name: FabricNotPrimaryException
  fullName: system.fabric.exception.FabricNotPrimaryException
  type: Class
  syntax:
    content: public class FabricNotPrimaryException extends FabricException
- uid: system.fabric.exception._fabric_not_readable_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_not_readable_exception.yml
  name: FabricNotReadableException
  fullName: system.fabric.exception.FabricNotReadableException
  type: Class
  syntax:
    content: public class FabricNotReadableException extends FabricException
- uid: system.fabric.exception._fabric_object_closed_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_object_closed_exception.yml
  name: FabricObjectClosedException
  fullName: system.fabric.exception.FabricObjectClosedException
  type: Class
  syntax:
    content: public class FabricObjectClosedException extends FabricException
- uid: system.fabric.exception._fabric_replication_operation_too_large_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_replication_operation_too_large_exception.yml
  name: FabricReplicationOperationTooLargeException
  fullName: system.fabric.exception.FabricReplicationOperationTooLargeException
  type: Class
  summary: <p>Exception indicating that the associated replication operation is larger than the configured limit </p>
  syntax:
    content: public class FabricReplicationOperationTooLargeException extends FabricException
- uid: system.fabric.exception._fabric_server_authentication_failed_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_server_authentication_failed_exception.yml
  name: FabricServerAuthenticationFailedException
  fullName: system.fabric.exception.FabricServerAuthenticationFailedException
  type: Class
  summary: <p>The exception that is thrown when server authentication failed. </p>
  syntax:
    content: public class FabricServerAuthenticationFailedException extends FabricException
- uid: system.fabric.exception._fabric_service_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_service_not_found_exception.yml
  name: FabricServiceNotFoundException
  fullName: system.fabric.exception.FabricServiceNotFoundException
  type: Class
  summary: <p>Exception indicating that there is no Service Found by that name. </p>
  syntax:
    content: public class FabricServiceNotFoundException extends FabricElementNotFoundException
- uid: system.fabric.exception._fabric_transient_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_transient_exception.yml
  name: FabricTransientException
  fullName: system.fabric.exception.FabricTransientException
  type: Class
  syntax:
    content: public class FabricTransientException extends FabricException
- uid: system.fabric.exception._invalid_reentrant_call_exception
  parent: system.fabric.exception
  href: system.fabric.exception._invalid_reentrant_call_exception.yml
  name: InvalidReentrantCallException
  fullName: system.fabric.exception.InvalidReentrantCallException
  type: Class
  syntax:
    content: public class InvalidReentrantCallException extends FabricException
- uid: system.fabric.exception._path_too_long_exception
  parent: system.fabric.exception
  href: system.fabric.exception._path_too_long_exception.yml
  name: PathTooLongException
  fullName: system.fabric.exception.PathTooLongException
  type: Class
  syntax:
    content: public class PathTooLongException extends FabricException
- uid: system.fabric.exception._reentrant_actor_invalid_state_exception
  parent: system.fabric.exception
  href: system.fabric.exception._reentrant_actor_invalid_state_exception.yml
  name: ReentrantActorInvalidStateException
  fullName: system.fabric.exception.ReentrantActorInvalidStateException
  type: Class
  syntax:
    content: public class ReentrantActorInvalidStateException extends FabricException
- uid: system.fabric.exception._unauthorized_access_exception
  parent: system.fabric.exception
  href: system.fabric.exception._unauthorized_access_exception.yml
  name: UnauthorizedAccessException
  fullName: system.fabric.exception.UnauthorizedAccessException
  type: Class
  summary: <p>Indicates mismatch between access credentials passed while creating visitor client object and the expected credentials that visitor services expects. </p>
  syntax:
    content: public class UnauthorizedAccessException extends FabricException
